{{- if eq .Values.environment "production" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: letsencrypt-prod
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "cert-manager-wrapper.chart" . }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.registrationEmail }}
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
{{- end }}
