replicaCount: 1

image:
  repository: docker.io/grafana/grafana
  # Need to use `grafana>=5.x` so that we can provision dashboards and
  # datasources via configuration files.
  #
  # Avoid migrating to grafana 6.x until necessary.
  tag: 5.4.3

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

# Allow Grafana to run on spot instances because we do not care if its high
# availaibility.
tolerations:
- key: "type"
  operator: "Equal"
  value: "spot-instance"

service:
  port: 3000
