# This manifest is responsible for creating the Secret the CoreOS Prometheus
# Operator requires to configure Alertmanager instances:
# https://coreos.com/operators/prometheus/docs/latest/user-guides/alerting.html.
# It must be a secret because `alertmanager.yaml` could contain sensitive
# tokens. See the README for how we handle the secrets.
apiVersion: v1
kind: Secret
metadata:
  # The Prometheus Operator requires we use the format `alertmanager-NAME`.
  name: alertmanager-{{ include "alertmanager.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "alertmanager.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "alertmanager.chart" . }}
  namespace: {{ .Values.namespace }}
data:
  # The base64 encoded configuration file for our Alertmanager (without any line
  # breaks).
  alertmanager.yaml: {{ .Values.alertmanager_yaml_base64 }}
