# This manifest declares the ServiceAccount with which our alertmanager pods will run.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertmanager.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "alertmanager.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "alertmanager.chart" . }}
  namespace: {{ .Values.namespace }}
