# This template defines the Service through which we'll access our pods.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "alertmanager.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "alertmanager.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if eq .Values.environment "production" }}
  type: {{ .Values.service.productionType }}
  {{- else }}
  type: {{ .Values.service.developmentType }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    # We custom specify the `alertmanager` label because the CoreOS Prometheus
    # operator copies it to the pods from the `alertmanager` resource.
    alertmanager: {{ include "alertmanager.name" . }}
