apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "prometheus-operator.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-operator.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "prometheus-operator.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-operator.name" . }}
      app.kubernetes.io/environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prometheus-operator.name" . }}
        app.kubernetes.io/environment: {{ .Values.environment }}
    spec:
      containers:
      - args:
{{ toYaml .Values.args | indent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
{{ toYaml .Values.resources | indent 10 }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      serviceAccountName: {{ include "prometheus-operator.name" . }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}

