---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      serviceAccountName: blog
      containers:
      - name: blog
        image: docker.io/mattjmcnaughton/blog:ae0a5cdbe37261de890aab5d5f987f04cb8d29c8
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
