---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      serviceAccountName: blog
      containers:
      - name: blog
        image: docker.io/mattjmcnaughton/blog:0b805208794fce961d21cc540290127df97742ed
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
