# Template for the Deployment managing the pods which serve our blog.
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "blog.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "blog.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "blog.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blog.name" . }}
      app.kubernetes.io/environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "blog.name" . }}
        app.kubernetes.io/environment: {{ .Values.environment }}
    spec:
      serviceAccountName: {{ include "blog.name" . }}
      containers:
      - name: blog
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
