---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: docker.io/mattjmcnaughton/blog:fcbb6c9cba65ddb05e2ae10db78e88e0d0b01441
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
