# Template for ingress of service
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "blog.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "blog.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "blog.chart" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if eq .Values.environment "production" }}
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
    {{- end }}
spec:
  tls:
  - hosts:
    - mattjmcnaughton.com
    - www.mattjmcnaughton.com
    - blog.mattjmcnaughton.com
    secretName: blog-tls
  rules:
    - host: mattjmcnaughton.com
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ include "blog.name" . }}
            servicePort: 80
    - host: www.mattjmcnaughton.com
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ include "blog.name" . }}
            servicePort: 80
    - host: blog.mattjmcnaughton.com
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ include "blog.name" . }}
            servicePort: 80
