---
# This manifest declares a RoleBinding binding the Blog role to the Blog
# ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: blog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blog
subjects:
- kind: ServiceAccount
  name: blog

