---
apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
