# This manifest declares the ServiceAccount with which our Blog pods will run.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blog.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "blog.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "blog.chart" . }}
  namespace: {{ .Values.namespace }}
