apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-exporter.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "node-exporter.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "node-exporter.chart" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-exporter.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-exporter.name" . }}
  namespace: {{ .Values.namespace }}
