# This manifest declares the DaemonSet responsible for managing the Pods which
# will export node metrics to prometheus. A DaemonSet ensures all eligible nodes
# run a copy of the pod.
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ include "node-exporter.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "node-exporter.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "node-exporter.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-exporter.name" . }}
      app.kubernetes.io/environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "node-exporter.name" . }}
        app.kubernetes.io/environment: {{ .Values.environment }}
    spec:
      containers:
      - args:
{{ toYaml .Values.nodeExporterArgs | indent 10 }}
        image: "{{ .Values.nodeExporterImage.repository }}:{{ .Values.nodeExporterImage.tag }}"
        name: node-exporter
        resources:
{{ toYaml .Values.nodeExporterResources | indent 10 }}
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: false
        - mountPath: /host/sys
          name: sys
          readOnly: false
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      - args:
{{ toYaml .Values.kubeRbacProxyArgs | indent 10 }}
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: "{{ .Values.kubeRbacProxyImage.repository }}:{{ .Values.kubeRbacProxyImage.tag }}"
        name: kube-rbac-proxy
        ports:
          # @TODO(mattjmcnaughton) Should I be working hard to include the port
          # in values.yaml somehow?
        - containerPort: 9100
          hostPort: 9100
          name: https
        resources:
{{ toYaml .Values.kubeRbacProxyResources | indent 10 }}
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: {{ include "node-exporter.name" . }}
      # Schedule this pod on the master, so we can get node resource usage on
      # the master as well.
      #
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
