# This manifest declares the Service, which allows Prometheus to access all
# node-exporters for scraping.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-exporter.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "node-exporter.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "node-exporter.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  # We use ClusterIP because we only want this endpoint accessible within the
  # cluster.
  clusterIP: None
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "node-exporter.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
