registrationEmail: mattjmcnaughton@gmail.com

cert-manager:
  nameOverride: cert-manager
  fullnameOverride: cert-manager

  image:
    tag: v0.6.2

  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 200m
      memory: 100Mi

  tolerations:
  - key: "type"
    operator: "Equal"
    value: "spot-instance"
