---
# This manifest declares that we want a Prometheus cluster deployed via the
# Prometheus operator. Note, in order to use the `Prometheus` CRD, we must first
# deploy CoreOS's Prometheus Operator.
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  # Our Prometheus cluster should have at least 2 replicas. Under the hood,
  # the Prometheus Operator creates a stateful set. So we will have `#replicas`
  # pods in our stateful set.
  replicas: 2
  # Retain data for 90 days. Note, we may need to decrease these if we find it
  # requires too much storage.
  retention: "90d"
  serviceAccountName: prometheus
  # ServiceMonitors specify how the Prometheus cluster should scrape metrics. We
  # attach `ServiceMonitors` we've defined to this Prometheus cluster using the
  # `serviceMonitorSelector`.
  serviceMonitorSelector:
    matchLabels:
      app: blog
  resources:
    requests:
      memory: 400Mi
  # @TODO(mattjmcnaughton) Determine a way to make this work when using
  # Minikube. I may need to wait until I'm templating this via a Helm chart.
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: prometheus-ssd
        resources:
          requests:
            storage: 20Gi
