---
# This manifest declares that we want a Prometheus cluster deployed via the
# Prometheus operator. Note, in order to use the `Prometheus` CRD, we must first
# deploy CoreOS's Prometheus Operator.
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  # Our Prometheus cluster should have at least 2 replicas. Under the hood,
  # the Prometheus Operator creates a stateful set. So we will have `#replicas`
  # pods in our stateful set.
  replicas: 2
  # Retain data for 90 days. Note, we may need to decrease these if we find it
  # requires too much storage.
  retention: "90d"
  serviceAccountName: prometheus
  # ServiceMonitors specify how the Prometheus cluster should scrape metrics. We
  # attach `ServiceMonitors` we've defined to this Prometheus cluster using the
  # `serviceMonitorSelector`.
  serviceMonitorSelector:
    matchLabels:
      role: service-monitor
  # PrometheusRules specify the rules under which Prometheus should fire alerts
  # (which are handeled by AlertManager). We attach `PrometheusRules` to our
  # `Prometheus` instance via the `ruleSelector`.
  ruleSelector:
    matchLabels:
      role: alert-rules
  # Configure our Prometheus instance to send alerts to the `alertmanager`
  # service.
  alerting:
    alertmanagers:
    # @TODO(mattjmcnaughton) We'll want to update/template this namespace once
    # we being making more advanced uses of namespaces.
    - namespace: default
      name: alertmanager
      port: web
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  # @TODO(mattjmcnaughton) Determine a way to make this work when using
  # Minikube. I may need to wait until I'm templating this via a Helm chart.
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: prometheus-ssd
        resources:
          requests:
            storage: 20Gi
