---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  # We temporarily use a ClusterIP, because I don't want this externally used
  # on the internet until we have some form of authentication. We can't have
  # some form of meaningful authentication until we have https. We can access it
  # from our local machine using port forwarding.
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
