---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  endpoints:
  - port: http
    interval: 5s
  namespaceSelector:
    matchNames:
      - default
