---
# This manifest declares the Service which allows us to access our Prometheus
# cluster (either internally or externally).
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "prometheus.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    # The CoreOS Prometheus operator assigns the `prometheus=prometheus` label
    # to all pods in the StatefulSet it creates for the Prometheus cluster.
    prometheus: prometheus
