{{- if eq .Values.environment "production" }}
# This manifest declares the StorageClass from which our Prometheus instance
# claims persistent storage. Note, we may eventually want to have a generic
# claim for using ssds that we can use across our entire cluster.
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: {{ include "prometheus.name" . }}-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
{{- end }}
