image:
  repository: docker.io/nextcloud
  tag: 15.0

# https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html
resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 512Mi

# Allow next-cloud to run on spot instances because we do not care if its high
# availaibility.
tolerations:
- key: "type"
  operator: "Equal"
  value: "spot-instance"

initScripts:
  # See instructions in README.md. For now, you must manually execute this
  # script after we first create our NextCloud instance.
  manual-first-boot.sh: |-
    #!/bin/bash
    for appToInstall in tasks calendar deck; do
      su -s /bin/bash -c "php occ app:install $appToInstall" www-data
    done

    for appToDisable in gallery activity; do
      su -s /bin/bash -c "php occ app:disable $appToDisable" www-data
    done

    su -s /bin/bash -c "export OC_PASS=$NEXTCLOUD_PERSONAL_PASSWORD; php occ user:add --password-from-env --group='admin' $NEXTCLOUD_PERSONAL_USER" www-data

service:
  type: NodePort
  port: 80

postgresql:
  # If we name this `next-cloud-postgres`, we will have naming collisions.
  nameOverride: next-cloud-postgres-db
  fullnameOverride: next-cloud-postgres-db

  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 9.6
    pullPolicy: IfNotPresent

  # _helm-environments defines if `enabled` is true or not. The settings below
  # only apply if `enabled=true`.
  persistence:
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  master:
    # Allow next-cloud postgres to run on spot instances because we do not care if its high
    # availaibility.
    #
    # @TODO(mattjmcnaughton) I'm not positive if this is a good idea...
    tolerations:
    - key: "type"
      operator: "Equal"
      value: "spot-instance"


  resources:
    limits:
      memory: 512Mi
      cpu: 512m
    requests:
      memory: 512Mi
      cpu: 512m

  # Need to set more conservative, especially for local development.
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1
