apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "next-cloud.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "next-cloud.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "next-cloud.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  # This value cannot be more than one, until EBS supports ReadWriteMany volumes.
  # If EBS does start supporting ReadWriteMany volumes, and we decided we wanted
  # to run multiple replicas, we would still need to convert from using a
  # Deployment to using a StatefulSet before creating multiple replicas.
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "next-cloud.name" . }}
      app.kubernetes.io/environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "next-cloud.name" . }}
        app.kubernetes.io/environment: {{ .Values.environment }}
    spec:
      serviceAccountName: {{ include "next-cloud.name" . }}
      containers:
      - name: next-cloud
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: next-cloud-persistent-storage
          mountPath: /var/www/html
        - name: configmap-scripts-volume
          mountPath: /bin/manual-first-boot.sh
          readOnly: true
          subPath: manual-first-boot.sh
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "next-cloud.name" . }}-admin
              key: username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "next-cloud.name" . }}-admin
              key: password
        - name: NEXTCLOUD_PERSONAL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "next-cloud.name" . }}-personal
              key: username
        - name: NEXTCLOUD_PERSONAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "next-cloud.name" . }}-personal
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "next-cloud.name" . }}-postgres
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "next-cloud.name" . }}-postgres
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "next-cloud.name" . }}-postgres
              key: password
        - name: POSTGRES_HOST
          value: {{ .Values.postgresql.fullnameOverride }}
      volumes:
        - name: next-cloud-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "next-cloud.name" . }}
        - name: configmap-scripts-volume
          configMap:
            name: {{ include "next-cloud.name" . }}-scripts
            defaultMode: 0700
