# This manifest declares the Deployment responsible for managing the Pods which
# run Grafana.
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "grafana.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "grafana.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}
      app.kubernetes.io/environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grafana.name" . }}
        app.kubernetes.io/environment: {{ .Values.environment }}
    spec:
      serviceAccountName: {{ include "grafana.name" . }}
      containers:
      - name: grafana
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "grafana.name" . }}-admin-password
              key: password
        # Mount the volumes containing all of the config files from our
        # ConfigMaps into the proper location.
        volumeMounts:
        - name: config-volume
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: config-volume
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
          subPath: datasource.yaml
        - name: config-volume
          mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
          subPath: dashboards.yaml
        - name: dashboards-volume
          mountPath: /var/lib/grafana/dashboards
      # Create volumes from our two different ConfigMaps. We can then mount
      # these volumes into the Pod, meaning the configuration files are now
      # available to Grafana.
      volumes:
        - name: config-volume
          configMap:
            name: grafana-config
        - name: dashboards-volume
          configMap:
            name: grafana-dashboards
