apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.name" . }}-admin-password
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "grafana.chart" . }}
  namespace: {{ .Values.namespace }}
data:
  password: {{ .Values.adminPassword | nospace | b64enc | quote }}
