# The template for the Service which allows access to our grafana.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "grafana.chart" . }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if eq .Values.environment "production" }}
  type: {{ .Values.service.productionType }}
  {{- else }}
  type: {{ .Values.service.developmentType }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
