# This manifest declares the ServiceAccount with which our grafana pods will run.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/environment: {{ .Values.environment }}
    helm.sh/chart: {{ include "grafana.chart" . }}
  namespace: {{ .Values.namespace }}

