replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: efa1d212b5056e98b731511513f165487bb79735

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
