replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: 43e07c938daae4c30e0ceb2cbfaf9c3e5aa827d8

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
