replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: a8d4702f854c124f3ea48da6afecbc9fd6dfbe53

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
