replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: 0fe6cde87079798618d8cb395aa8895a523d229f

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
