replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: 9fe1dc679d5543dc8ddac941a3414bddeedeb478

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
