replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: 479eda6a68787c2aa584aec6948751299398575e

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
