replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: f8fce85349c1b08b33aa53eb5e0504907e2f846a

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
