replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: 7616e32ec2321726561bf43215c04385c0bda399

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
