replicaCount: 2

image:
  repository: docker.io/mattjmcnaughton/blog
  tag: 388207c23f4ca5eb250ac0c887274c2e25cba0a9

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

service:
  port: 80
